version: '3'
services:
  irisdb:
    container_name: irisdb
    image: postgres:9.5
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=iris
    - POSTGRES_PASSWORD=iris
    networks:
    - iris_net
  iris:
    container_name: iris
    image: tns/iris
    ports:
    - 8080:8080
    - 8787:8787
    depends_on:
    - irisdb
    env_file:
    - dev.env
    networks:
    - iris_net
networks:
  iris_net:
    driver: bridge